# Generated by Django 5.0.4 on 2024-06-07 04:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmblemasModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField(max_length=30, null=True)),
                ('moedas', models.FloatField(default=0.0)),
                ('datatime', models.DateTimeField(default=django.utils.timezone.now)),
                ('icone', models.ImageField(upload_to='imagens/')),
                ('solicitante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitanteemblemas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmblemaCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solicitante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comprador', to=settings.AUTH_USER_MODEL)),
                ('emblema', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Loja.emblemasmodel')),
            ],
        ),
    ]
