# Generated by Django 5.0.4 on 2024-06-15 08:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Loja', '0002_moedavalor_moedasaque'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MoedaSaqueMoedaValor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField(max_length=30, null=True)),
                ('icone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Loja.moedavalor')),
                ('solicitante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='militarsaque', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='MoedaSaque',
        ),
    ]
