# Generated by Django 5.0.4 on 2024-06-03 04:42

import django.db.models.deletion
import django.utils.timezone
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaginaSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField(max_length=30, null=True)),
                ('categoria', models.CharField(choices=[('Grupos', 'Grupos'), ('Apostilas', 'Apostilas'), ('Escolas e Institutos', 'Escolas e Institutos'), ('Novidades', 'Novidades')], max_length=30, null=True)),
                ('descricao', models.TextField(max_length=70, null=True)),
                ('texto', django_ckeditor_5.fields.CKEditor5Field(default=' ', verbose_name='Postagem')),
                ('datatime', models.DateTimeField(default=django.utils.timezone.now)),
                ('icone', models.ImageField(upload_to='imagens/')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('ordenador', models.PositiveIntegerField(default=0)),
                ('solicitante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitantepágina', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LogPáginas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(max_length=150, null=True, verbose_name='Texto paginas')),
                ('datatime', models.DateTimeField(default=django.utils.timezone.now)),
                ('treinamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Site.paginasite', verbose_name='paginas')),
            ],
        ),
    ]
