# Generated by Django 5.0.4 on 2024-06-03 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paginasite',
            name='categoria',
            field=models.CharField(choices=[('Grupos', 'Grupos'), ('Apostilas', 'Apostilas'), ('Escolas e Institutos', 'Escolas e Institutos'), ('Novidades', 'Novidades'), ('Team Speak', 'Team Speak'), ('Hierarquia', 'Hierarquia')], max_length=30, null=True),
        ),
    ]
