# Generated by Django 5.0.4 on 2024-06-07 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Honrarias', '0002_honrariamilitar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='honrariasregistro',
            name='descricao',
            field=models.TextField(max_length=400, null=True),
        ),
    ]
