# Generated by Django 5.0.4 on 2024-05-29 22:41

import Treinamentos.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatoriosDeTreinamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('treinamento', models.CharField(choices=[('', 'Selecione o treinamento'), ('Básico I', 'Básico I'), ('Básico II', 'Básico II'), ('Complementar I', 'Complementar I'), ('Complementar II', 'Complementar II')], max_length=50, null=True)),
                ('sala', models.CharField(choices=[('CI', 'CI'), ('CT', 'CT')], max_length=50, null=True)),
                ('treinados', models.TextField(blank=True, max_length=50, null=True)),
                ('hora_ino', models.TimeField(null=True)),
                ('hora_fim', models.TimeField(null=True)),
                ('alistado_cont', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=2, null=True)),
                ('reprovado_cont', models.CharField(choices=[('0', '0 Aprovados'), ('1', '1 Aprovado'), ('2', '2 Aprovados'), ('3', '3 Aprovados'), ('4', '4 Aprovados'), ('5', '5 Aprovados'), ('6', '6 Aprovados'), ('7', '7 Aprovados'), ('8', '8 Aprovados'), ('9', '9 Aprovados'), ('10', '10 Aprovados')], max_length=2, null=True)),
                ('categoria', models.CharField(choices=[('Recruta(s)', 'Recruta(s)'), ('Soldado(s)', 'Soldado(s)'), ('Cabo(s)', 'Cabo(s)'), ('Cabo(s) Estrela', 'Cabo(s) Estrela')], max_length=50, null=True)),
                ('reprovacoes', models.TextField(max_length=250, null=True)),
                ('aprovados', models.TextField(default=' ', max_length=250, null=True)),
                ('obs', models.CharField(blank=True, max_length=250, null=True)),
                ('status', models.CharField(choices=[('Aprovado', 'Aprovado'), ('Em análise...', 'Em análise...'), ('Reprovado', 'Reprovado')], default='Em análise...', max_length=50, null=True)),
                ('motivo', models.TextField(blank=True, max_length=250, null=True)),
                ('aprovador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aprovador', to=settings.AUTH_USER_MODEL)),
                ('auxiliar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auxiliar', to=settings.AUTH_USER_MODEL, validators=[Treinamentos.models.RelatoriosDeTreinamento.Validador_Auxiliar])),
                ('ofc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='oficial', to=settings.AUTH_USER_MODEL)),
                ('solicitante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitante', to=settings.AUTH_USER_MODEL)),
                ('treinador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treinador', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LogRelatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(max_length=150, null=True, verbose_name='Texto relatorio')),
                ('datatime', models.DateTimeField(default=django.utils.timezone.now)),
                ('relatorio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Treinamentos.relatoriosdetreinamento', verbose_name='relatorio')),
            ],
        ),
    ]
