# Generated by Django 5.0.4 on 2024-05-31 02:05

import Treinamentos.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Treinamentos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatoriosdetreinamento',
            name='auxiliar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auxiliar', to=settings.AUTH_USER_MODEL, validators=[Treinamentos.models.RelatoriosDeTreinamento.Validador_Auxiliar]),
        ),
    ]
