# Generated by Django 5.0.4 on 2024-05-31 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Treinamentos', '0004_treinamentos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logrelatorio',
            name='relatorio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Treinamentos.treinamentos', verbose_name='relatorio'),
        ),
    ]
