# Generated by Django 5.0.4 on 2024-05-31 04:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Treinamentos', '0006_remove_logrelatorio_relatorio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logrelatorio',
            name='treinamento',
        ),
        migrations.AddField(
            model_name='logrelatorio',
            name='relatorio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Treinamentos.relatoriosdetreinamento', verbose_name='relatorio'),
        ),
        migrations.CreateModel(
            name='LogTreinamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(max_length=150, null=True, verbose_name='Texto relatorio')),
                ('datatime', models.DateTimeField(default=django.utils.timezone.now)),
                ('treinamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Treinamentos.treinamentos', verbose_name='treinamento')),
            ],
        ),
    ]
