# Generated by Django 5.0.4 on 2024-05-31 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Treinamentos', '0007_remove_logrelatorio_treinamento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treinamentos',
            name='solicitante',
        ),
        migrations.DeleteModel(
            name='LogTreinamento',
        ),
        migrations.DeleteModel(
            name='Treinamentos',
        ),
    ]
