# Generated by Django 5.0.4 on 2024-11-26 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Treinamentos', '0008_remove_treinamentos_solicitante_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatoriosdetreinamento',
            name='categoria',
            field=models.CharField(choices=[('Recruta(s)', 'Recruta(s)'), ('Soldado(s)', 'Soldado(s)'), ('Cabo(s)', 'Cabo(s)'), ('Aluno', 'Aluno')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='relatoriosdetreinamento',
            name='sala',
            field=models.CharField(choices=[('Sala de T1', 'Sala de T1'), ('Sala de T2', 'Sala de T2'), ('Sala Robótica', 'Sala Robótica'), ('Centro de Instrução', 'Centro de Instrução')], max_length=50, null=True),
        ),
    ]
