# Generated by Django 5.0.4 on 2024-06-09 08:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Re',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abertura', models.DateTimeField(default=django.utils.timezone.now)),
                ('fechamento', models.DateTimeField(default=django.utils.timezone.now)),
                ('recrutados', models.TextField(default=' ', max_length=250, null=True)),
                ('status', models.CharField(choices=[('Aprovado', 'Aprovado'), ('Em análise...', 'Em análise...'), ('Reprovado', 'Reprovado')], default='Em análise...', max_length=50, null=True)),
                ('ofc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='oficialre', to=settings.AUTH_USER_MODEL)),
                ('solicitante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LogRE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(max_length=150, null=True, verbose_name='Texto RE')),
                ('datatime', models.DateTimeField(default=django.utils.timezone.now)),
                ('aval', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Recrutamento.re', verbose_name='aval')),
            ],
        ),
    ]
