# Generated by Django 5.0.4 on 2024-06-09 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Recrutamento', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logre',
            old_name='aval',
            new_name='re',
        ),
    ]
