# Generated by Django 5.0.4 on 2024-08-01 00:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recrutamento', '0002_rename_aval_logre_re'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='re',
            name='status',
        ),
        migrations.AddField(
            model_name='re',
            name='militar',
            field=models.TextField(default=' ', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='logre',
            name='re',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Recrutamento.re', verbose_name='re'),
        ),
    ]
