# Generated by Django 5.0.4 on 2024-08-01 02:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recrutamento', '0004_re_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='re',
            name='abertura',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='re',
            name='fechamento',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
