# Generated by Django 5.0.4 on 2024-11-26 22:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recrutamento', '0007_rm'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='re',
            name='ofc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='oficialre', to=settings.AUTH_USER_MODEL, verbose_name='Oficial Responsável'),
        ),
        migrations.AlterField(
            model_name='rm',
            name='ofc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='oficialrm', to=settings.AUTH_USER_MODEL, verbose_name='Oficial Responsável'),
        ),
        migrations.AlterField(
            model_name='rm',
            name='presentes',
            field=models.TextField(default=' ', max_length=250, null=True, verbose_name='Oficiais Presentes'),
        ),
    ]
