# Generated by Django 5.0.4 on 2024-06-02 00:33

import django.db.models.deletion
import django.utils.timezone
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostagemJornal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField(max_length=30, null=True)),
                ('descricao', models.TextField(max_length=30, null=True)),
                ('texto', django_ckeditor_5.fields.CKEditor5Field(default=' ', verbose_name='Treinamentos')),
                ('datatime', models.DateTimeField(default=django.utils.timezone.now)),
                ('imagem', models.ImageField(upload_to='imagens/')),
                ('solicitante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitantepostagem', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LogPostagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(max_length=150, null=True, verbose_name='Texto postagem')),
                ('datatime', models.DateTimeField(default=django.utils.timezone.now)),
                ('treinamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Jornal.postagemjornal', verbose_name='postagem')),
            ],
        ),
    ]
