# Generated by Django 5.0.4 on 2024-06-02 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jornal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postagemjornal',
            name='categoria',
            field=models.TextField(max_length=30, null=True),
        ),
    ]
