# Generated by Django 5.0.4 on 2024-06-02 01:06

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jornal', '0002_postagemjornal_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postagemjornal',
            name='descricao',
            field=models.TextField(max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='postagemjornal',
            name='texto',
            field=django_ckeditor_5.fields.CKEditor5Field(default=' ', verbose_name='Postagem'),
        ),
    ]
