# Generated by Django 5.0.4 on 2024-06-03 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jornal', '0003_alter_postagemjornal_descricao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postagemjornal',
            name='categoria',
            field=models.CharField(choices=[('Aposentadorias', 'Aposentadorias'), ('Inaugurações', 'Inaugurações'), ('Formaturas', 'Formaturas'), ('Novidades', 'Novidades')], max_length=30, null=True),
        ),
    ]
