# Generated by Django 5.0.4 on 2024-06-03 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jornal', '0004_alter_postagemjornal_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='postagemjornal',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
