# Generated by Django 5.0.4 on 2024-06-04 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jornal', '0005_postagemjornal_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postagemjornal',
            name='categoria',
            field=models.CharField(choices=[('Aposentadorias', 'Aposentadorias'), ('Promoções', 'Promoções'), ('Inaugurações', 'Inaugurações'), ('Formaturas', 'Formaturas'), ('Novidades', 'Novidades')], max_length=30, null=True),
        ),
    ]
