# Generated by Django 5.0.4 on 2024-06-16 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Supervisores', '0002_destaquesupervisor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='palestrasupervisores',
            name='titulo',
            field=models.TextField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='supervisorrelatorio',
            name='patente_treinado',
            field=models.CharField(blank=True, choices=[('', 'Selecione a Patente'), ('Cabo', 'Cabo'), ('Aluno', 'Aluno'), ('Terceiro Sargento', 'Terceiro Sargento'), ('Segundo Sargento', 'Segundo Sargento'), ('Primeiro Sargento', 'Primeiro Sargento'), ('Subtenente', 'Subtenente'), ('Cadete', 'Cadete')], max_length=50, null=True),
        ),
    ]
