# Generated by Django 5.0.4 on 2024-06-16 21:58

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SegundaCIA', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AvaliaçãoTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('treinador_nick', models.TextField(blank=True, max_length=20, null=True)),
                ('tp', models.CharField(choices=[('', 'Selecione o tipo de TP'), ('Tp1', 'Tp1'), ('Tp2', 'Tp2'), ('Tp3', 'Tp3'), ('Tp4', 'Tp4')], max_length=50, null=True)),
                ('solicitante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Destaque2CIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datatime', models.DateTimeField(default=django.utils.timezone.now)),
                ('militar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='militardestaque2cia', to=settings.AUTH_USER_MODEL)),
                ('solicitante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitantedest2cia', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Relatório2CIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('hora_ino', models.TimeField(null=True)),
                ('hora_fim', models.TimeField(null=True)),
                ('treinador_patente', models.CharField(choices=[('', 'Selecione a patente'), ('Terceiro Sargento', 'Terceiro Sargento'), ('Segundo Sargento', 'Segundo Sargento'), ('Primeiro Sargento', 'Primeiro Sargento'), ('Subtenente', 'Subtenente'), ('Cadete', 'Cadete')], max_length=50, null=True)),
                ('treinador_nick', models.TextField(blank=True, max_length=20, null=True)),
                ('avaliador_patente', models.CharField(choices=[('', 'Selecione a patente'), ('Segundo Tenente', 'Segundo Tenente'), ('Primeiro Tenente', 'Primeiro Tenente'), ('Capitão', 'Capitão'), ('Major', 'Major'), ('Tenente-Coronel', 'Tenente-Coronel')], max_length=50, null=True)),
                ('treinamento', models.CharField(choices=[('', 'Selecione o treinamento'), ('Básico I', 'Básico I'), ('Básico II', 'Básico II'), ('Complementar I', 'Complementar I'), ('Complementar II', 'Complementar II'), ('Robotizado I', 'Robotizado I'), ('Robotizado II', 'Robotizado II')], max_length=50, null=True)),
                ('ortografia', models.DecimalField(decimal_places=1, default=0.0, help_text='Digite um valor entre 0,0 e 4,0', max_digits=2)),
                ('agilidade', models.DecimalField(decimal_places=1, default=0.0, help_text='Digite um valor entre 0,0 e 1,0', max_digits=2, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('aprofundamento', models.DecimalField(decimal_places=1, default=0.0, help_text='Digite um valor entre 0,0 e 5,0', max_digits=2, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('total', models.DecimalField(decimal_places=1, default=0.0, help_text='Digite um valor entre 0,0 e 10,0', max_digits=3)),
                ('obs', models.TextField(blank=True, max_length=250, null=True)),
                ('avaliador', models.ForeignKey(limit_choices_to={'groups__name': 'M2CIA'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
