# Generated by Django 5.0.4 on 2024-05-21 22:59

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datatime', models.DateTimeField(default=django.utils.timezone.now)),
                ('duracao', models.CharField(choices=[('', 'Selecione a Duração do Aval'), ('7 Dias', '7 Dias'), ('15 Dias', '15 Dias'), ('31 Dias', '31 Dias')], max_length=50, null=True)),
                ('motivo', models.TextField(max_length=150, null=True, verbose_name='Motivo')),
                ('data', models.DateField(default=datetime.date.today, null=True)),
                ('data2', models.DateField(default=datetime.date.today, null=True)),
                ('status', models.CharField(choices=[('Aprovado', 'Aprovado'), ('Em análise...', 'Em análise...'), ('Reprovado', 'Reprovado')], default='Em análise...', max_length=50, null=True)),
                ('solicitante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LogJA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(max_length=150, null=True, verbose_name='Texto Aval')),
                ('datatime', models.DateTimeField(default=django.utils.timezone.now)),
                ('aval', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Avais.ja', verbose_name='aval')),
            ],
        ),
    ]
