# Generated by Django 5.0.4 on 2024-06-16 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ajudantes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ajudanterelatorio',
            old_name='treinador_nick',
            new_name='treinador',
        ),
    ]
