# Generated by Django 5.0.4 on 2024-05-03 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Militares', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='militarusuario',
            name='moedas',
            field=models.FloatField(default=0.0),
        ),
    ]
