# Generated by Django 5.0.4 on 2024-05-29 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Militares', '0002_militarusuario_moedas'),
    ]

    operations = [
        migrations.AddField(
            model_name='militarusuario',
            name='patente_order',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
