# Generated by Django 5.0.4 on 2024-07-27 00:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Militares', '0004_militarusuario_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='militarusuario',
            name='username',
            field=models.CharField(help_text='150 characters or fewer. Letters (uppercase and lowercase), digits, @, :, -, and _ only.', max_length=150, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_username', message='Enter a valid username. This value may contain only letters (uppercase and lowercase), numbers, @, :, -, and _ characters.', regex='^[a-zA-Z0-9@_:.,-!]+$')], verbose_name='usuário'),
        ),
    ]
