# Generated by Django 5.0.4 on 2024-11-26 22:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Militares', '0006_alter_militarusuario_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='militarusuario',
            name='siglas',
            field=models.CharField(blank=True, choices=[('<T1>', '<T1>'), ('<T2>', '<T2>'), ('<T1> <T1R>', '<T1> <T1R>'), ('<T2> <TRB2>', '<T2> <TRB2>'), ('<T3> <TRB2>', '<T3> <TRB2>'), ('<T4> <TRB2>', '<T4> <TRB2>')], max_length=50),
        ),
        migrations.AlterField(
            model_name='militarusuario',
            name='username',
            field=models.CharField(help_text='150 characters or fewer. Letters (uppercase and lowercase), digits, @, :, -, and _ only.', max_length=150, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_username', message='Enter a valid username. This value may contain only letters (uppercase and lowercase), numbers, @, :, -, and _ characters.', regex='^[a-zA-Z0-9@_:.,\\-!=]+$')], verbose_name='usuário'),
        ),
    ]
