# Generated by Django 5.0.4 on 2024-07-29 01:54

import django.db.models.deletion
import django.utils.timezone
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DestaqueMonitores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datatime', models.DateTimeField(default=django.utils.timezone.now)),
                ('militar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='militardestaquemon', to=settings.AUTH_USER_MODEL)),
                ('solicitante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitantedestmon', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GuiaMonitores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guia', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Guia')),
                ('datatime', models.DateTimeField(default=django.utils.timezone.now)),
                ('solicitante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitantemon', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MonitorRelatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('treinamento', models.CharField(choices=[('Treinamento Básico I', 'Treinamento Básico I'), ('Treinamento Básico II', 'Treinamento Básico II'), ('Treinamento Complementar I', 'Treinamento Complementar I'), ('Treinamento Complementar II', 'Treinamento Complementar II')], max_length=50, null=True)),
                ('patente_treinado', models.CharField(blank=True, choices=[('', 'Selecione a Patente'), ('Cabo', 'Cabo'), ('Aluno', 'Aluno'), ('Terceiro Sargento', 'Terceiro Sargento'), ('Segundo Sargento', 'Segundo Sargento'), ('Primeiro Sargento', 'Primeiro Sargento'), ('Subtenente', 'Subtenente'), ('Cadete', 'Cadete')], max_length=50, null=True)),
                ('treinados', models.TextField(blank=True, max_length=50, null=True)),
                ('treinador_nick', models.TextField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(choices=[('Aprovado', 'Aprovado'), ('Em análise...', 'Em análise...'), ('Reprovado', 'Reprovado')], default='Em análise...', max_length=50, null=True)),
                ('solicitante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
